basePath: /
definitions:
  events.EventDetail:
    properties:
      created_at:
        type: string
      event_time:
        type: string
      id:
        type: integer
      name:
        type: string
      ticket_booked:
        type: integer
      ticket_price:
        type: string
      ticket_remains:
        type: integer
      total_tickets:
        type: integer
    type: object
  events.EventList:
    properties:
      created_at:
        type: string
      event_time:
        type: string
      id:
        type: integer
      name:
        type: string
      ticket_price:
        type: string
      total_tickets:
        type: integer
    type: object
  responses.EventList:
    properties:
      events:
        items:
          $ref: '#/definitions/events.EventList'
        type: array
    type: object
  responses.MyError:
    properties:
      message:
        type: string
    type: object
host: localhost:11300
info:
  contact: {}
  title: Ticket booking API documentation
  version: 0.1.0
paths:
  /events:
    get:
      description: Get all events
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.EventList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MyError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.MyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MyError'
      summary: Get all events
      tags:
      - Events
  /events/{id}:
    get:
      description: Get event detail
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/events.EventDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MyError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.MyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MyError'
      summary: Get event detail
      tags:
      - Events
swagger: "2.0"
